//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Maestro SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.Profisee_Customer360Service.Contracts.MemberDataContracts
{
    using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
    using Profisee.Services.Sdk.Common.Contracts.DataObjects;
    using System;
	using System.Collections.Generic;
    using System.Runtime.Serialization;

	// Only for Restful services that return a list of members...
    [CollectionDataContract]
    public class AccountMemberList : List<AccountMember>
    {
        public AccountMemberList() { }
        public AccountMemberList(List<AccountMember> members) : base(members) { }
    }

	[System.Runtime.Serialization.DataContract()]
	public class AccountMember : BaseMemberType
	{
				
		private string _AccountID;
				
		private string _BillingCity;
				
		private string _BillingCountry;
				
		private string _BillingStateProvince;
				
		private string _BillingStreet;
				
		private string _BillingZipPostalCode;
				
		private Nullable<double> _MatchScore;
				
		private string _Phone;
				
		private string _Website;
		
		private AccountMember.NullificationMask _Nullify;

		public AccountMember()
		{
			_Nullify = new AccountMember.NullificationMask();
		}
				

		[System.Runtime.Serialization.DataMember()]
		public string AccountID
		{
			get 
			{
				return this._AccountID;
			}
			set
			{
				this._AccountID = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public string BillingCity
		{
			get 
			{
				return this._BillingCity;
			}
			set
			{
				this._BillingCity = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public string BillingCountry
		{
			get 
			{
				return this._BillingCountry;
			}
			set
			{
				this._BillingCountry = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public string BillingStateProvince
		{
			get 
			{
				return this._BillingStateProvince;
			}
			set
			{
				this._BillingStateProvince = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public string BillingStreet
		{
			get 
			{
				return this._BillingStreet;
			}
			set
			{
				this._BillingStreet = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public string BillingZipPostalCode
		{
			get 
			{
				return this._BillingZipPostalCode;
			}
			set
			{
				this._BillingZipPostalCode = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public Nullable<double> MatchScore
		{
			get 
			{
				return this._MatchScore;
			}
			set
			{
				this._MatchScore = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public string Phone
		{
			get 
			{
				return this._Phone;
			}
			set
			{
				this._Phone = value;
			}
		}


				

		[System.Runtime.Serialization.DataMember()]
		public string Website
		{
			get 
			{
				return this._Website;
			}
			set
			{
				this._Website = value;
			}
		}


				
		[System.Runtime.Serialization.DataMember()]
		public AccountMember.NullificationMask Nullify
		{
			get
			{
				return this._Nullify;
			}
			set
			{
				this._Nullify = value;
			}
		}

		[System.Runtime.Serialization.DataContract()]
		public class NullificationMask
		{
							
			private bool _AccountID;
							
			private bool _BillingCity;
							
			private bool _BillingCountry;
							
			private bool _BillingStateProvince;
							
			private bool _BillingStreet;
							
			private bool _BillingZipPostalCode;
							
			private bool _MatchScore;
							
			private bool _Phone;
							
			private bool _Website;
			
		[System.Runtime.Serialization.DataMember()]
		public bool AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				this._AccountID = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool BillingCity
		{
			get
			{
				return this._BillingCity;
			}
			set
			{
				this._BillingCity = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool BillingCountry
		{
			get
			{
				return this._BillingCountry;
			}
			set
			{
				this._BillingCountry = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool BillingStateProvince
		{
			get
			{
				return this._BillingStateProvince;
			}
			set
			{
				this._BillingStateProvince = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool BillingStreet
		{
			get
			{
				return this._BillingStreet;
			}
			set
			{
				this._BillingStreet = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool BillingZipPostalCode
		{
			get
			{
				return this._BillingZipPostalCode;
			}
			set
			{
				this._BillingZipPostalCode = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool MatchScore
		{
			get
			{
				return this._MatchScore;
			}
			set
			{
				this._MatchScore = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				this._Phone = value;
			}
		}


		[System.Runtime.Serialization.DataMember()]
		public bool Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				this._Website = value;
			}
		}

		}
	}
} 

