//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Profisee SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.AccountService.ServiceLibrary.MemberAdapters
{
    using Mdm.AccountService.Contracts.MemberDataContracts;
	using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
    using Profisee.Services.Sdk.AcceleratorFramework;
    using Profisee.Services.Sdk.Common.Contracts.DataObjects;
    using System;

	public class AccountMemberAdapter : MdmBaseMemberAdapter
	{

		private AccountMember _StrongType;

		public AccountMemberAdapter() :
				base()
		{
		}
		
		private string MatchEmail
		{
			get
			{
				return ((string)(base.GetMemberValue("MatchEmail")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "MatchEmail",
						Id = new Guid("8b32361a-554b-4ef4-8a01-9890c6bbadfc")
					},
					value,
					this._StrongType.Nullify.MatchEmail);
			}
		}

		
		private string MatchPhone
		{
			get
			{
				return ((string)(base.GetMemberValue("MatchPhone")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "MatchPhone",
						Id = new Guid("e836a112-3e6c-410e-a425-e2e0fa1be5ef")
					},
					value,
					this._StrongType.Nullify.MatchPhone);
			}
		}

		
		private Nullable<double> MatchScore
		{
			get
			{
				return ((Nullable<double>)(base.GetMemberValue("MatchScore")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "MatchScore",
						Id = new Guid("74bd0654-4a4c-478f-ad1e-b3bba5f6d044")
					},
					value,
					this._StrongType.Nullify.MatchScore);
			}
		}

		
		private string StdAddressLine1
		{
			get
			{
				return ((string)(base.GetMemberValue("StdAddressLine1")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "StdAddressLine1",
						Id = new Guid("06b74a49-ff62-4abc-b12b-a486293b4ec4")
					},
					value,
					this._StrongType.Nullify.StdAddressLine1);
			}
		}

		
		private string StdCity
		{
			get
			{
				return ((string)(base.GetMemberValue("StdCity")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "StdCity",
						Id = new Guid("529eed9d-eb49-4800-8464-d180fe905858")
					},
					value,
					this._StrongType.Nullify.StdCity);
			}
		}

		
		private string StdPostalCode
		{
			get
			{
				return ((string)(base.GetMemberValue("StdPostalCode")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "StdPostalCode",
						Id = new Guid("37a83877-661d-40dd-a01d-09383ee2017c")
					},
					value,
					this._StrongType.Nullify.StdPostalCode);
			}
		}

		
		private string StdStateProvince
		{
			get
			{
				return ((string)(base.GetMemberValue("StdStateProvince")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "StdStateProvince",
						Id = new Guid("458dc7e1-6169-4e40-8303-683756b390e1")
					},
					value,
					this._StrongType.Nullify.StdStateProvince);
			}
		}

		
		private string SourceCode
		{
			get
			{
				return ((string)(base.GetMemberValue("SourceCode")));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = "SourceCode",
						Id = new Guid("42d1852e-6f8c-4d71-bc69-a7b1b125bcda")
					},
					value,
					this._StrongType.Nullify.SourceCode);
			}
		}

		
		protected override BaseMemberType Transform(Member internalMember)
		{
			_StrongType = new AccountMember();
			base.Transform(_StrongType, internalMember);
						
			_StrongType.MatchEmail = this.MatchEmail;

						
			_StrongType.MatchPhone = this.MatchPhone;

						
			_StrongType.MatchScore = this.MatchScore;

						
			_StrongType.StdAddressLine1 = this.StdAddressLine1;

						
			_StrongType.StdCity = this.StdCity;

						
			_StrongType.StdPostalCode = this.StdPostalCode;

						
			_StrongType.StdStateProvince = this.StdStateProvince;

						
			_StrongType.SourceCode = this.SourceCode;

			 
			return _StrongType;
		}

		protected override Member Transform(BaseMemberType externalMember)
		{
			Member internalMember;
			internalMember = base.Transform(externalMember);
			_StrongType = ((AccountMember)(externalMember));
            if ((this._StrongType.Nullify == null))
            {
                this._StrongType.Nullify = new AccountMember.NullificationMask();
            }
				
			this.MatchEmail = _StrongType.MatchEmail;

				
			this.MatchPhone = _StrongType.MatchPhone;

				
			this.MatchScore = _StrongType.MatchScore;

				
			this.StdAddressLine1 = _StrongType.StdAddressLine1;

				
			this.StdCity = _StrongType.StdCity;

				
			this.StdPostalCode = _StrongType.StdPostalCode;

				
			this.StdStateProvince = _StrongType.StdStateProvince;

				
			this.SourceCode = _StrongType.SourceCode;

			 
			return internalMember;
		}
	}
}
