//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Maestro SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.Profisee_Customer360Service.Contracts.MemberDataContracts
{
    using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
    using Profisee.Services.Sdk.Common.Contracts.DataObjects;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    // Only for Restful services that return a list of members...
    [CollectionDataContract]
    public class CustomerMemberList : List<CustomerMember>
    {
        public CustomerMemberList() { }
        public CustomerMemberList(List<CustomerMember> members) : base(members) { }
    }

    [System.Runtime.Serialization.DataContract()]
    public class CustomerMember : BaseMemberType
    {

        private string _AddressKey;

        private string _AddressLine1;

        private string _AddressLine2;

        private MemberIdentifier _AddressLookupStatus;

        private string _AddressType;

        private Nullable<double> _ApprovedCount;

        private string _BestTimetoCallFrom;

        private string _BestTimetoCallTo;

        private MemberIdentifier _BillingCurrency;

        private string _CarrierRoute;

        private string _CBSACode;

        private string _CBSADivisionCode;

        private string _CBSADivisionLevel;

        private string _CBSADivisionTitle;

        private string _CBSALevel;

        private string _CBSATitle;

        private string _CensusBlock;

        private string _CensusTract;

        private string _City;

        private string _Comment;

        private string _ContactFullName;

        private string _Country;

        private string _CountyFIPS;

        private string _CountyName;

        private Nullable<double> _CreditLimit;

        private MemberIdentifier _CustomerStatus;

        private string _DeliveryPointCheckDigit;

        private string _DeliveryPointCode;

        private MemberIdentifier _DoNotEmail;

        private MemberIdentifier _DoNotFax;

        private MemberIdentifier _DoNotPhone;

        private string _DynamicsCRMID;

        private string _EmailVerificationResults;

        private MemberIdentifier _EmailVerificationStatus;

        private string _EmailAddress;

        private string _FirstName;

        private string _FullName;

        private string _FullAddress;

        private string _GoogleMapsLink;

        private MemberIdentifier _Industry;

        private string _LastName;

        private Nullable<double> _LastMonthSales;

        private Nullable<double> _Latitude;

        private string _LiveStatus;

        private MemberIdentifier _LocationConfidence;

        private Nullable<double> _LocationResponseCount;

        private MemberIdentifier _LocationVerificationStatus;

        private Nullable<double> _Longitude;

        private Nullable<double> _MatchScore;

        private string _MiddleName;

        private string _NameParsingResults;

        private MemberIdentifier _NameParsingStatus;

        private MemberIdentifier _PartyType;

        private MemberIdentifier _PaymentTerms;

        private string _PhoneNumber;

        private string _PhoneVerificationResults;

        private MemberIdentifier _PhoneVerificationStatus;

        private string _PlaceCode;

        private string _PlaceName;

        private string _Plus4;

        private string _PMBName;

        private string _PMBNumber;

        private string _PostDirection;

        private string _PostalCode;

        private string _PreDirection;

        private MemberIdentifier _PreferredCommunication;

        private Nullable<double> _ProposedCount;

        private MemberIdentifier _Region;

        private string _RejectionReason;

        private string _SalesforceID;

        private MemberIdentifier _SourceSystem;

        private string _StateProvince;

        private MemberIdentifier _Status;

        private string _StreetName;

        private string _StreetNumber;

        private string _StreetSuffix;

        private string _SuiteName;

        private string _SuiteNumber;

        private string _TaxID;

        private MemberIdentifier _ValidationAction;

        private MemberIdentifier _WorkflowStatus;

        private string _ZIPType;

        private CustomerMember.NullificationMask _Nullify;

        public CustomerMember()
        {
            _Nullify = new CustomerMember.NullificationMask();
        }


        [System.Runtime.Serialization.DataMember()]
        public string AddressKey
        {
            get
            {
                return this._AddressKey;
            }
            set
            {
                this._AddressKey = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string AddressLine1
        {
            get
            {
                return this._AddressLine1;
            }
            set
            {
                this._AddressLine1 = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string AddressLine2
        {
            get
            {
                return this._AddressLine2;
            }
            set
            {
                this._AddressLine2 = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier AddressLookupStatus
        {
            get
            {
                return this._AddressLookupStatus;
            }
            set
            {
                this._AddressLookupStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string AddressType
        {
            get
            {
                return this._AddressType;
            }
            set
            {
                this._AddressType = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> ApprovedCount
        {
            get
            {
                return this._ApprovedCount;
            }
            set
            {
                this._ApprovedCount = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string BestTimetoCallFrom
        {
            get
            {
                return this._BestTimetoCallFrom;
            }
            set
            {
                this._BestTimetoCallFrom = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string BestTimetoCallTo
        {
            get
            {
                return this._BestTimetoCallTo;
            }
            set
            {
                this._BestTimetoCallTo = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier BillingCurrency
        {
            get
            {
                return this._BillingCurrency;
            }
            set
            {
                this._BillingCurrency = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CarrierRoute
        {
            get
            {
                return this._CarrierRoute;
            }
            set
            {
                this._CarrierRoute = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CBSACode
        {
            get
            {
                return this._CBSACode;
            }
            set
            {
                this._CBSACode = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CBSADivisionCode
        {
            get
            {
                return this._CBSADivisionCode;
            }
            set
            {
                this._CBSADivisionCode = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CBSADivisionLevel
        {
            get
            {
                return this._CBSADivisionLevel;
            }
            set
            {
                this._CBSADivisionLevel = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CBSADivisionTitle
        {
            get
            {
                return this._CBSADivisionTitle;
            }
            set
            {
                this._CBSADivisionTitle = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CBSALevel
        {
            get
            {
                return this._CBSALevel;
            }
            set
            {
                this._CBSALevel = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CBSATitle
        {
            get
            {
                return this._CBSATitle;
            }
            set
            {
                this._CBSATitle = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CensusBlock
        {
            get
            {
                return this._CensusBlock;
            }
            set
            {
                this._CensusBlock = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CensusTract
        {
            get
            {
                return this._CensusTract;
            }
            set
            {
                this._CensusTract = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this._Comment = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string ContactFullName
        {
            get
            {
                return this._ContactFullName;
            }
            set
            {
                this._ContactFullName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this._Country = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CountyFIPS
        {
            get
            {
                return this._CountyFIPS;
            }
            set
            {
                this._CountyFIPS = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string CountyName
        {
            get
            {
                return this._CountyName;
            }
            set
            {
                this._CountyName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> CreditLimit
        {
            get
            {
                return this._CreditLimit;
            }
            set
            {
                this._CreditLimit = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier CustomerStatus
        {
            get
            {
                return this._CustomerStatus;
            }
            set
            {
                this._CustomerStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string DeliveryPointCheckDigit
        {
            get
            {
                return this._DeliveryPointCheckDigit;
            }
            set
            {
                this._DeliveryPointCheckDigit = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string DeliveryPointCode
        {
            get
            {
                return this._DeliveryPointCode;
            }
            set
            {
                this._DeliveryPointCode = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier DoNotEmail
        {
            get
            {
                return this._DoNotEmail;
            }
            set
            {
                this._DoNotEmail = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier DoNotFax
        {
            get
            {
                return this._DoNotFax;
            }
            set
            {
                this._DoNotFax = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier DoNotPhone
        {
            get
            {
                return this._DoNotPhone;
            }
            set
            {
                this._DoNotPhone = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string DynamicsCRMID
        {
            get
            {
                return this._DynamicsCRMID;
            }
            set
            {
                this._DynamicsCRMID = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string EmailVerificationResults
        {
            get
            {
                return this._EmailVerificationResults;
            }
            set
            {
                this._EmailVerificationResults = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier EmailVerificationStatus
        {
            get
            {
                return this._EmailVerificationStatus;
            }
            set
            {
                this._EmailVerificationStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this._EmailAddress = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this._FirstName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string FullName
        {
            get
            {
                return this._FullName;
            }
            set
            {
                this._FullName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string FullAddress
        {
            get
            {
                return this._FullAddress;
            }
            set
            {
                this._FullAddress = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string GoogleMapsLink
        {
            get
            {
                return this._GoogleMapsLink;
            }
            set
            {
                this._GoogleMapsLink = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier Industry
        {
            get
            {
                return this._Industry;
            }
            set
            {
                this._Industry = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this._LastName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> LastMonthSales
        {
            get
            {
                return this._LastMonthSales;
            }
            set
            {
                this._LastMonthSales = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this._Latitude = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string LiveStatus
        {
            get
            {
                return this._LiveStatus;
            }
            set
            {
                this._LiveStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier LocationConfidence
        {
            get
            {
                return this._LocationConfidence;
            }
            set
            {
                this._LocationConfidence = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> LocationResponseCount
        {
            get
            {
                return this._LocationResponseCount;
            }
            set
            {
                this._LocationResponseCount = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier LocationVerificationStatus
        {
            get
            {
                return this._LocationVerificationStatus;
            }
            set
            {
                this._LocationVerificationStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this._Longitude = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> MatchScore
        {
            get
            {
                return this._MatchScore;
            }
            set
            {
                this._MatchScore = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this._MiddleName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string NameParsingResults
        {
            get
            {
                return this._NameParsingResults;
            }
            set
            {
                this._NameParsingResults = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier NameParsingStatus
        {
            get
            {
                return this._NameParsingStatus;
            }
            set
            {
                this._NameParsingStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier PartyType
        {
            get
            {
                return this._PartyType;
            }
            set
            {
                this._PartyType = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier PaymentTerms
        {
            get
            {
                return this._PaymentTerms;
            }
            set
            {
                this._PaymentTerms = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this._PhoneNumber = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PhoneVerificationResults
        {
            get
            {
                return this._PhoneVerificationResults;
            }
            set
            {
                this._PhoneVerificationResults = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier PhoneVerificationStatus
        {
            get
            {
                return this._PhoneVerificationStatus;
            }
            set
            {
                this._PhoneVerificationStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PlaceCode
        {
            get
            {
                return this._PlaceCode;
            }
            set
            {
                this._PlaceCode = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PlaceName
        {
            get
            {
                return this._PlaceName;
            }
            set
            {
                this._PlaceName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string Plus4
        {
            get
            {
                return this._Plus4;
            }
            set
            {
                this._Plus4 = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PMBName
        {
            get
            {
                return this._PMBName;
            }
            set
            {
                this._PMBName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PMBNumber
        {
            get
            {
                return this._PMBNumber;
            }
            set
            {
                this._PMBNumber = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PostDirection
        {
            get
            {
                return this._PostDirection;
            }
            set
            {
                this._PostDirection = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this._PostalCode = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string PreDirection
        {
            get
            {
                return this._PreDirection;
            }
            set
            {
                this._PreDirection = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier PreferredCommunication
        {
            get
            {
                return this._PreferredCommunication;
            }
            set
            {
                this._PreferredCommunication = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public Nullable<double> ProposedCount
        {
            get
            {
                return this._ProposedCount;
            }
            set
            {
                this._ProposedCount = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier Region
        {
            get
            {
                return this._Region;
            }
            set
            {
                this._Region = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string RejectionReason
        {
            get
            {
                return this._RejectionReason;
            }
            set
            {
                this._RejectionReason = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string SalesforceID
        {
            get
            {
                return this._SalesforceID;
            }
            set
            {
                this._SalesforceID = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier SourceSystem
        {
            get
            {
                return this._SourceSystem;
            }
            set
            {
                this._SourceSystem = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string StateProvince
        {
            get
            {
                return this._StateProvince;
            }
            set
            {
                this._StateProvince = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string StreetName
        {
            get
            {
                return this._StreetName;
            }
            set
            {
                this._StreetName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string StreetNumber
        {
            get
            {
                return this._StreetNumber;
            }
            set
            {
                this._StreetNumber = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string StreetSuffix
        {
            get
            {
                return this._StreetSuffix;
            }
            set
            {
                this._StreetSuffix = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string SuiteName
        {
            get
            {
                return this._SuiteName;
            }
            set
            {
                this._SuiteName = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string SuiteNumber
        {
            get
            {
                return this._SuiteNumber;
            }
            set
            {
                this._SuiteNumber = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string TaxID
        {
            get
            {
                return this._TaxID;
            }
            set
            {
                this._TaxID = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier ValidationAction
        {
            get
            {
                return this._ValidationAction;
            }
            set
            {
                this._ValidationAction = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public MemberIdentifier WorkflowStatus
        {
            get
            {
                return this._WorkflowStatus;
            }
            set
            {
                this._WorkflowStatus = value;
            }
        }




        [System.Runtime.Serialization.DataMember()]
        public string ZIPType
        {
            get
            {
                return this._ZIPType;
            }
            set
            {
                this._ZIPType = value;
            }
        }



        [System.Runtime.Serialization.DataMember()]
        public CustomerMember.NullificationMask Nullify
        {
            get
            {
                return this._Nullify;
            }
            set
            {
                this._Nullify = value;
            }
        }

        [System.Runtime.Serialization.DataContract()]
        public class NullificationMask
        {

            private bool _AddressKey;

            private bool _AddressLine1;

            private bool _AddressLine2;

            private bool _AddressLookupStatus;

            private bool _AddressType;

            private bool _ApprovedCount;

            private bool _BestTimetoCallFrom;

            private bool _BestTimetoCallTo;

            private bool _BillingCurrency;

            private bool _CarrierRoute;

            private bool _CBSACode;

            private bool _CBSADivisionCode;

            private bool _CBSADivisionLevel;

            private bool _CBSADivisionTitle;

            private bool _CBSALevel;

            private bool _CBSATitle;

            private bool _CensusBlock;

            private bool _CensusTract;

            private bool _City;

            private bool _Comment;

            private bool _ContactFullName;

            private bool _Country;

            private bool _CountyFIPS;

            private bool _CountyName;

            private bool _CreditLimit;

            private bool _CustomerStatus;

            private bool _DeliveryPointCheckDigit;

            private bool _DeliveryPointCode;

            private bool _DoNotEmail;

            private bool _DoNotFax;

            private bool _DoNotPhone;

            private bool _DynamicsCRMID;

            private bool _EmailVerificationResults;

            private bool _EmailVerificationStatus;

            private bool _EmailAddress;

            private bool _FirstName;

            private bool _FullName;

            private bool _FullAddress;

            private bool _GoogleMapsLink;

            private bool _Industry;

            private bool _LastName;

            private bool _LastMonthSales;

            private bool _Latitude;

            private bool _LiveStatus;

            private bool _LocationConfidence;

            private bool _LocationResponseCount;

            private bool _LocationVerificationStatus;

            private bool _Longitude;

            private bool _MatchScore;

            private bool _MiddleName;

            private bool _NameParsingResults;

            private bool _NameParsingStatus;

            private bool _PartyType;

            private bool _PaymentTerms;

            private bool _PhoneNumber;

            private bool _PhoneVerificationResults;

            private bool _PhoneVerificationStatus;

            private bool _PlaceCode;

            private bool _PlaceName;

            private bool _Plus4;

            private bool _PMBName;

            private bool _PMBNumber;

            private bool _PostDirection;

            private bool _PostalCode;

            private bool _PreDirection;

            private bool _PreferredCommunication;

            private bool _ProposedCount;

            private bool _Region;

            private bool _RejectionReason;

            private bool _SalesforceID;

            private bool _SourceSystem;

            private bool _StateProvince;

            private bool _Status;

            private bool _StreetName;

            private bool _StreetNumber;

            private bool _StreetSuffix;

            private bool _SuiteName;

            private bool _SuiteNumber;

            private bool _TaxID;

            private bool _ValidationAction;

            private bool _WorkflowStatus;

            private bool _ZIPType;

            [System.Runtime.Serialization.DataMember()]
            public bool AddressKey
            {
                get
                {
                    return this._AddressKey;
                }
                set
                {
                    this._AddressKey = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool AddressLine1
            {
                get
                {
                    return this._AddressLine1;
                }
                set
                {
                    this._AddressLine1 = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool AddressLine2
            {
                get
                {
                    return this._AddressLine2;
                }
                set
                {
                    this._AddressLine2 = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool AddressLookupStatus
            {
                get
                {
                    return this._AddressLookupStatus;
                }
                set
                {
                    this._AddressLookupStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool AddressType
            {
                get
                {
                    return this._AddressType;
                }
                set
                {
                    this._AddressType = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool ApprovedCount
            {
                get
                {
                    return this._ApprovedCount;
                }
                set
                {
                    this._ApprovedCount = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool BestTimetoCallFrom
            {
                get
                {
                    return this._BestTimetoCallFrom;
                }
                set
                {
                    this._BestTimetoCallFrom = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool BestTimetoCallTo
            {
                get
                {
                    return this._BestTimetoCallTo;
                }
                set
                {
                    this._BestTimetoCallTo = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool BillingCurrency
            {
                get
                {
                    return this._BillingCurrency;
                }
                set
                {
                    this._BillingCurrency = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CarrierRoute
            {
                get
                {
                    return this._CarrierRoute;
                }
                set
                {
                    this._CarrierRoute = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CBSACode
            {
                get
                {
                    return this._CBSACode;
                }
                set
                {
                    this._CBSACode = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CBSADivisionCode
            {
                get
                {
                    return this._CBSADivisionCode;
                }
                set
                {
                    this._CBSADivisionCode = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CBSADivisionLevel
            {
                get
                {
                    return this._CBSADivisionLevel;
                }
                set
                {
                    this._CBSADivisionLevel = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CBSADivisionTitle
            {
                get
                {
                    return this._CBSADivisionTitle;
                }
                set
                {
                    this._CBSADivisionTitle = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CBSALevel
            {
                get
                {
                    return this._CBSALevel;
                }
                set
                {
                    this._CBSALevel = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CBSATitle
            {
                get
                {
                    return this._CBSATitle;
                }
                set
                {
                    this._CBSATitle = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CensusBlock
            {
                get
                {
                    return this._CensusBlock;
                }
                set
                {
                    this._CensusBlock = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CensusTract
            {
                get
                {
                    return this._CensusTract;
                }
                set
                {
                    this._CensusTract = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool City
            {
                get
                {
                    return this._City;
                }
                set
                {
                    this._City = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Comment
            {
                get
                {
                    return this._Comment;
                }
                set
                {
                    this._Comment = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool ContactFullName
            {
                get
                {
                    return this._ContactFullName;
                }
                set
                {
                    this._ContactFullName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Country
            {
                get
                {
                    return this._Country;
                }
                set
                {
                    this._Country = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CountyFIPS
            {
                get
                {
                    return this._CountyFIPS;
                }
                set
                {
                    this._CountyFIPS = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CountyName
            {
                get
                {
                    return this._CountyName;
                }
                set
                {
                    this._CountyName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CreditLimit
            {
                get
                {
                    return this._CreditLimit;
                }
                set
                {
                    this._CreditLimit = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool CustomerStatus
            {
                get
                {
                    return this._CustomerStatus;
                }
                set
                {
                    this._CustomerStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool DeliveryPointCheckDigit
            {
                get
                {
                    return this._DeliveryPointCheckDigit;
                }
                set
                {
                    this._DeliveryPointCheckDigit = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool DeliveryPointCode
            {
                get
                {
                    return this._DeliveryPointCode;
                }
                set
                {
                    this._DeliveryPointCode = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool DoNotEmail
            {
                get
                {
                    return this._DoNotEmail;
                }
                set
                {
                    this._DoNotEmail = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool DoNotFax
            {
                get
                {
                    return this._DoNotFax;
                }
                set
                {
                    this._DoNotFax = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool DoNotPhone
            {
                get
                {
                    return this._DoNotPhone;
                }
                set
                {
                    this._DoNotPhone = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool DynamicsCRMID
            {
                get
                {
                    return this._DynamicsCRMID;
                }
                set
                {
                    this._DynamicsCRMID = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool EmailVerificationResults
            {
                get
                {
                    return this._EmailVerificationResults;
                }
                set
                {
                    this._EmailVerificationResults = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool EmailVerificationStatus
            {
                get
                {
                    return this._EmailVerificationStatus;
                }
                set
                {
                    this._EmailVerificationStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool EmailAddress
            {
                get
                {
                    return this._EmailAddress;
                }
                set
                {
                    this._EmailAddress = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool FirstName
            {
                get
                {
                    return this._FirstName;
                }
                set
                {
                    this._FirstName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool FullName
            {
                get
                {
                    return this._FullName;
                }
                set
                {
                    this._FullName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool FullAddress
            {
                get
                {
                    return this._FullAddress;
                }
                set
                {
                    this._FullAddress = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool GoogleMapsLink
            {
                get
                {
                    return this._GoogleMapsLink;
                }
                set
                {
                    this._GoogleMapsLink = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Industry
            {
                get
                {
                    return this._Industry;
                }
                set
                {
                    this._Industry = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool LastName
            {
                get
                {
                    return this._LastName;
                }
                set
                {
                    this._LastName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool LastMonthSales
            {
                get
                {
                    return this._LastMonthSales;
                }
                set
                {
                    this._LastMonthSales = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Latitude
            {
                get
                {
                    return this._Latitude;
                }
                set
                {
                    this._Latitude = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool LiveStatus
            {
                get
                {
                    return this._LiveStatus;
                }
                set
                {
                    this._LiveStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool LocationConfidence
            {
                get
                {
                    return this._LocationConfidence;
                }
                set
                {
                    this._LocationConfidence = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool LocationResponseCount
            {
                get
                {
                    return this._LocationResponseCount;
                }
                set
                {
                    this._LocationResponseCount = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool LocationVerificationStatus
            {
                get
                {
                    return this._LocationVerificationStatus;
                }
                set
                {
                    this._LocationVerificationStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Longitude
            {
                get
                {
                    return this._Longitude;
                }
                set
                {
                    this._Longitude = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool MatchScore
            {
                get
                {
                    return this._MatchScore;
                }
                set
                {
                    this._MatchScore = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool MiddleName
            {
                get
                {
                    return this._MiddleName;
                }
                set
                {
                    this._MiddleName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool NameParsingResults
            {
                get
                {
                    return this._NameParsingResults;
                }
                set
                {
                    this._NameParsingResults = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool NameParsingStatus
            {
                get
                {
                    return this._NameParsingStatus;
                }
                set
                {
                    this._NameParsingStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PartyType
            {
                get
                {
                    return this._PartyType;
                }
                set
                {
                    this._PartyType = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PaymentTerms
            {
                get
                {
                    return this._PaymentTerms;
                }
                set
                {
                    this._PaymentTerms = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PhoneNumber
            {
                get
                {
                    return this._PhoneNumber;
                }
                set
                {
                    this._PhoneNumber = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PhoneVerificationResults
            {
                get
                {
                    return this._PhoneVerificationResults;
                }
                set
                {
                    this._PhoneVerificationResults = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PhoneVerificationStatus
            {
                get
                {
                    return this._PhoneVerificationStatus;
                }
                set
                {
                    this._PhoneVerificationStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PlaceCode
            {
                get
                {
                    return this._PlaceCode;
                }
                set
                {
                    this._PlaceCode = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PlaceName
            {
                get
                {
                    return this._PlaceName;
                }
                set
                {
                    this._PlaceName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Plus4
            {
                get
                {
                    return this._Plus4;
                }
                set
                {
                    this._Plus4 = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PMBName
            {
                get
                {
                    return this._PMBName;
                }
                set
                {
                    this._PMBName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PMBNumber
            {
                get
                {
                    return this._PMBNumber;
                }
                set
                {
                    this._PMBNumber = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PostDirection
            {
                get
                {
                    return this._PostDirection;
                }
                set
                {
                    this._PostDirection = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PostalCode
            {
                get
                {
                    return this._PostalCode;
                }
                set
                {
                    this._PostalCode = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PreDirection
            {
                get
                {
                    return this._PreDirection;
                }
                set
                {
                    this._PreDirection = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool PreferredCommunication
            {
                get
                {
                    return this._PreferredCommunication;
                }
                set
                {
                    this._PreferredCommunication = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool ProposedCount
            {
                get
                {
                    return this._ProposedCount;
                }
                set
                {
                    this._ProposedCount = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Region
            {
                get
                {
                    return this._Region;
                }
                set
                {
                    this._Region = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool RejectionReason
            {
                get
                {
                    return this._RejectionReason;
                }
                set
                {
                    this._RejectionReason = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool SalesforceID
            {
                get
                {
                    return this._SalesforceID;
                }
                set
                {
                    this._SalesforceID = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool SourceSystem
            {
                get
                {
                    return this._SourceSystem;
                }
                set
                {
                    this._SourceSystem = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool StateProvince
            {
                get
                {
                    return this._StateProvince;
                }
                set
                {
                    this._StateProvince = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool Status
            {
                get
                {
                    return this._Status;
                }
                set
                {
                    this._Status = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool StreetName
            {
                get
                {
                    return this._StreetName;
                }
                set
                {
                    this._StreetName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool StreetNumber
            {
                get
                {
                    return this._StreetNumber;
                }
                set
                {
                    this._StreetNumber = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool StreetSuffix
            {
                get
                {
                    return this._StreetSuffix;
                }
                set
                {
                    this._StreetSuffix = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool SuiteName
            {
                get
                {
                    return this._SuiteName;
                }
                set
                {
                    this._SuiteName = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool SuiteNumber
            {
                get
                {
                    return this._SuiteNumber;
                }
                set
                {
                    this._SuiteNumber = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool TaxID
            {
                get
                {
                    return this._TaxID;
                }
                set
                {
                    this._TaxID = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool ValidationAction
            {
                get
                {
                    return this._ValidationAction;
                }
                set
                {
                    this._ValidationAction = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool WorkflowStatus
            {
                get
                {
                    return this._WorkflowStatus;
                }
                set
                {
                    this._WorkflowStatus = value;
                }
            }


            [System.Runtime.Serialization.DataMember()]
            public bool ZIPType
            {
                get
                {
                    return this._ZIPType;
                }
                set
                {
                    this._ZIPType = value;
                }
            }

        }
    }
}

