using Profisee.MasterDataMaestro.Services.DataContracts;
using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
using Profisee.Services.Sdk.Common.Contracts.DataContext;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ServiceModel;
using Mdm.Profisee_Customer360Service.Contracts.MemberDataContracts;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Maestro SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.Profisee_Customer360Service.Contracts.EntityServiceContracts
{
    
    
    [System.ServiceModel.ServiceContract(SessionMode=SessionMode.Allowed)]
    public interface ICustomerEntityOperations
    {

	    [System.ServiceModel.OperationContract()]
        CustomerMember GetCustomerMember(String memberCode);
        
		[System.ServiceModel.OperationContract()]
        Collection<CustomerMember> GetCustomerMembers(BrowseEntityContext browseContext);
        
        [System.ServiceModel.OperationContract()]
        Collection<CustomerMember> GetCustomerMembersUsingIds(Collection<MemberIdentifier> memberIds);
        
        [System.ServiceModel.OperationContract()]
        Collection<Error> AddCustomerMember(CustomerMember member);
        
        [System.ServiceModel.OperationContract()]
        Collection<Error> AddCustomerMemberWithIdReturn(CustomerMember member, out MemberIdentifier memberId);
        
        [System.ServiceModel.OperationContract()]
        Collection<Error> AddCustomerMembers(Collection<CustomerMember> members);
        
		[System.ServiceModel.OperationContract()]
        Collection<Error> AddCustomerMembersWithIdReturn(Collection<CustomerMember> member, out Collection<MemberIdentifier> memberIds);

        [System.ServiceModel.OperationContract()]
        Collection<Error> MergeCustomerMember(CustomerMember member);
        
        [System.ServiceModel.OperationContract()]
        Collection<Error> MergeCustomerMembers(Collection<CustomerMember> members);

		[System.ServiceModel.OperationContract()]
        Collection<Error> UpdateCustomerMember(CustomerMember member);
        
        [System.ServiceModel.OperationContract()]
        Collection<Error> UpdateCustomerMembers(Collection<CustomerMember> members);
        
        [System.ServiceModel.OperationContract()]
        Collection<Error> DeleteCustomerMember(String memberCode);
        
        [System.ServiceModel.OperationContract()]
        Collection<Error> DeleteCustomerMembers(Collection<String> memberCodes);       
	}
}
