//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Maestro SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.Profisee_Customer360Service.ServiceLibrary.MemberAdapters
{
    using Mdm.Profisee_Customer360Service.Contracts.MemberDataContracts;
	using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
    using Profisee.Services.Sdk.AcceleratorFramework;
    using Profisee.Services.Sdk.Common.Contracts.DataObjects;
    using System;
	using System.Configuration;

	public class AccountMemberAdapter : MdmBaseMemberAdapter
	{

		private AccountMember _StrongType;

		public AccountMemberAdapter() :
				base()
		{
		}
		
		private string AccountID
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.SalesforceID"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.SalesforceID"),
						Id = new Guid("8faa8c21-52e8-412a-867f-a2aece06e751")
					},
					value,
					this._StrongType.Nullify.AccountID);
			}
		}

		
		private string BillingCity
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingCity"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingCity"),
						Id = new Guid("814302fb-7c6e-474c-acd9-03d59a3f81d0")
					},
					value,
					this._StrongType.Nullify.BillingCity);
			}
		}

		
		private string BillingCountry
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingCountry"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingCountry"),
						Id = new Guid("baed3794-6ada-4df5-9da8-57f7a65c6faa")
					},
					value,
					this._StrongType.Nullify.BillingCountry);
			}
		}

		
		private string BillingStateProvince
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingState"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingState"),
						Id = new Guid("48cac26b-c9d1-4213-9142-fe1294cb2e07")
					},
					value,
					this._StrongType.Nullify.BillingStateProvince);
			}
		}

		
		private string BillingStreet
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingAddress"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingAddress"),
						Id = new Guid("b04e810c-4176-4636-85ba-0d6ac2fff519")
					},
					value,
					this._StrongType.Nullify.BillingStreet);
			}
		}

		
		private string BillingZipPostalCode
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingPostalCode"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.BillingPostalCode"),
						Id = new Guid("09a0bd13-6223-451a-8419-7342bf77c784")
					},
					value,
					this._StrongType.Nullify.BillingZipPostalCode);
			}
		}

		
		private Nullable<double> MatchScore
		{
			get
			{
				return ((Nullable<double>)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.MatchScore"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.MatchScore"),
						Id = new Guid("320d1157-4594-4e6c-af46-c8d2ff139152")
					},
					value,
					this._StrongType.Nullify.MatchScore);
			}
		}

		
		private string Phone
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.Phone"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.Phone"),
						Id = new Guid("3f5d8b8f-6546-4e4f-9c0b-d27544c6f333")
					},
					value,
					this._StrongType.Nullify.Phone);
			}
		}

		
		private string Website
		{
			get
			{
				return ((string)(base.GetMemberValue(ConfigurationManager.AppSettings.Get("MaestroAttribute.Website"))));
			}
			set
			{
				base.SetMemberValue(
					new Identifier
					{
						Name = ConfigurationManager.AppSettings.Get("MaestroAttribute.Website"),
						Id = new Guid("ec07f15d-a95b-41e9-a2bb-2a149ec5a117")
					},
					value,
					this._StrongType.Nullify.Website);
			}
		}

		
		protected override BaseMemberType Transform(Member internalMember)
		{
			_StrongType = new AccountMember();
			base.Transform(_StrongType, internalMember);
						
			_StrongType.AccountID = this.AccountID;

						
			_StrongType.BillingCity = this.BillingCity;

						
			_StrongType.BillingCountry = this.BillingCountry;

						
			_StrongType.BillingStateProvince = this.BillingStateProvince;

						
			_StrongType.BillingStreet = this.BillingStreet;

						
			_StrongType.BillingZipPostalCode = this.BillingZipPostalCode;

						
			_StrongType.MatchScore = this.MatchScore;

						
			_StrongType.Phone = this.Phone;

						
			_StrongType.Website = this.Website;

			 
			return _StrongType;
		}

		protected override Member Transform(BaseMemberType externalMember)
		{
			Member internalMember;
			internalMember = base.Transform(externalMember);
			_StrongType = ((AccountMember)(externalMember));
            if ((this._StrongType.Nullify == null))
            {
                this._StrongType.Nullify = new AccountMember.NullificationMask();
            }
				
			this.AccountID = _StrongType.AccountID;

				
			this.BillingCity = _StrongType.BillingCity;

				
			this.BillingCountry = _StrongType.BillingCountry;

				
			this.BillingStateProvince = _StrongType.BillingStateProvince;

				
			this.BillingStreet = _StrongType.BillingStreet;

				
			this.BillingZipPostalCode = _StrongType.BillingZipPostalCode;

				
			this.MatchScore = _StrongType.MatchScore;

				
			this.Phone = _StrongType.Phone;

				
			this.Website = _StrongType.Website;

			 
			return internalMember;
		}
	}
}
