//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Profisee SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.AccountService.Contracts.EntityServiceContracts
{
    using Mdm.AccountService.Contracts.MemberDataContracts;
    using Profisee.MasterDataMaestro.Services.DataContracts;
    using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
	using Profisee.Services.Sdk.Common.Contracts.DataContext;
    using System;
	using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ServiceModel;
    
    [System.ServiceModel.ServiceContract(SessionMode=SessionMode.Allowed)]
    public interface IAccountEntityOperations
    {

	    [System.ServiceModel.OperationContract()]
        AccountMember GetAccountMember(String memberCode);
        
		[System.ServiceModel.OperationContract()]
        Collection<AccountMember> GetAccountMembers(BrowseEntityContext browseContext);
        
        [System.ServiceModel.OperationContract()]
        Collection<AccountMember> GetAccountMembersUsingIds(Collection<MemberIdentifier> memberIds);
        
        	}
}
