//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Profisee SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Mdm.AccountService.Contracts
{
    using Mdm.AccountService.Contracts.EntityServiceContracts;
    using Profisee.Services.Sdk.Common.Contracts.ServiceContracts;
    using System.ServiceModel;
    
    /// <remarks>
    /// This interface defines the service contract associated with the <see cref="Account">.
    /// This interface and file should not be edited directly. User-defined custom
    /// service operation definitions should be added to the <see cref="IAccountExtensions"> interface from
    /// which this interface inherits.
    /// </remarks>
    [System.ServiceModel.ServiceContract(Namespace="http://schemas.profisee.com/masterdatamaestro/servicesbuilder/Maestro", SessionMode=SessionMode.Allowed)]
    public interface IAccount : IMdmModelService, IAccountExtensions, IAccountEntityOperations
    {
    }
}

