//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Profisee SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.AccountService.ServiceREST
{
    using Mdm.AccountService.Contracts.MemberDataContracts;
    using Mdm.AccountService.ServiceLibrary;
    using Profisee.MasterDataMaestro.Services.DataContracts;
	using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
    using System.Collections.Generic;
	using System.Configuration;
	using System.Runtime.Serialization;
	using System.ServiceModel;
	using System.ServiceModel.Web;
	using System;
	using System.Collections.ObjectModel;

    [SwaggerWcf.Attributes.SwaggerWcf("Account")]
    public partial class Account : IAccount
    {

  //      [SwaggerWcf.Attributes.SwaggerWcfTag("Account Member")]
  //      public AccountMember GetAccountMember(string code)
  //      {
  //          Account service = new Account();
  //          return service.GetAccountMember(code);
  //      }
		

  //      [SwaggerWcf.Attributes.SwaggerWcfTag("Account Member")]
		//public AccountMemberList GetAccountMemberList()
  //      {
  //          Account service = new Account();
  //          var members = service.GetAccountMembers(
  //              new Profisee.Services.Sdk.Common.Contracts.DataContext.BrowseEntityContext
  //              {
  //                  PageNumber = 1,
		//			PageSize = 50,
  //              });

  //          var memberList = new List<AccountMember>(members);
  //          return new AccountMemberList(memberList);
  //      }

  //      [SwaggerWcf.Attributes.SwaggerWcfTag("Account Member")]
		//public AccountMemberList GetAccountMemberList_Filter(string filter)
  //      {
  //          Account service = new Account();
  //          var members = service.GetAccountMembers(
  //              new Profisee.Services.Sdk.Common.Contracts.DataContext.BrowseEntityContext
  //              {
  //                  PageNumber = 1,
		//			PageSize = 50,
		//			Filter = filter
  //              });

  //          var memberList = new List<AccountMember>(members);
  //          return new AccountMemberList(memberList);
  //      }

  //      [SwaggerWcf.Attributes.SwaggerWcfTag("Account Member")]
		//public AccountMemberList GetAccountMemberList_PageNumberPageSize(string pageNumber, string pageSize)
  //      {
		//	int _pageNumber = Convert.ToInt32(pageNumber);
  //          int _pageSize = Convert.ToInt32(pageSize);
  //          Account service = new Account();
  //          var members = service.GetAccountMembers(
  //              new Profisee.Services.Sdk.Common.Contracts.DataContext.BrowseEntityContext
  //              {
  //                  PageNumber = _pageNumber,
		//			PageSize = _pageSize,
  //              });

  //          var memberList = new List<AccountMember>(members);
  //          return new AccountMemberList(memberList);
  //      }

  //      [SwaggerWcf.Attributes.SwaggerWcfTag("Account Member")]
		//public AccountMemberList GetFilteredAccountMemberList(string filter, string pageNumber, string pageSize)
  //      {
		//	int _pageNumber = Convert.ToInt32(pageNumber);
		//	int _pageSize = Convert.ToInt32(pageSize);
  //          Account service = new Account();
  //          var members = service.GetAccountMembers(
  //              new Profisee.Services.Sdk.Common.Contracts.DataContext.BrowseEntityContext
  //              {
		//			Filter = filter,
  //                  PageNumber = _pageNumber,
		//			PageSize = _pageSize
  //              });

  //          var memberList = new List<AccountMember>(members);
  //          return new AccountMemberList(memberList);
  //      }









	}
}