using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
using Profisee.Services.Sdk.AcceleratorFramework;
using Profisee.Services.Sdk.Common.Contracts.DataObjects;
using System;
using Mdm.Profisee_Customer360Service.Contracts.EntityServiceContracts;
using Mdm.Profisee_Customer360Service.Contracts.MemberDataContracts;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Maestro SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.Profisee_Customer360Service.ServiceLibrary.MemberAdapters
{
    public class CustomerMemberAdapter : MdmBaseMemberAdapter
    {

        private CustomerMember _StrongType;

        public CustomerMemberAdapter() :
                base()
        {
        }

        private string AddressKey
        {
            get
            {
                return ((string)(base.GetMemberValue("Address Key")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Address Key",
                        Id = new Guid("423ac104-1db2-403b-a832-0f33f70b0684")
                    },
                    value,
                    this._StrongType.Nullify.AddressKey);
            }
        }


        private string AddressLine1
        {
            get
            {
                return ((string)(base.GetMemberValue("Address Line 1")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Address Line 1",
                        Id = new Guid("dd953704-b0ab-43fd-942b-6994c2fe365a")
                    },
                    value,
                    this._StrongType.Nullify.AddressLine1);
            }
        }


        private string AddressLine2
        {
            get
            {
                return ((string)(base.GetMemberValue("Address Line 2")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Address Line 2",
                        Id = new Guid("acf1cd3f-b1b3-428a-953c-92a203874073")
                    },
                    value,
                    this._StrongType.Nullify.AddressLine2);
            }
        }


        private MemberIdentifier AddressLookupStatus
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Address Lookup Status")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Address Lookup Status",
                        Id = new Guid("c165b926-a560-41c4-a63a-df568dacf9ab")
                    },
                    value,
                    this._StrongType.Nullify.AddressLookupStatus);
            }
        }


        private string AddressType
        {
            get
            {
                return ((string)(base.GetMemberValue("Address Type")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Address Type",
                        Id = new Guid("dd429b21-f56c-4713-ac50-325eff3bbb45")
                    },
                    value,
                    this._StrongType.Nullify.AddressType);
            }
        }


        private Nullable<double> ApprovedCount
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("Approved Count")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Approved Count",
                        Id = new Guid("f768df27-de9d-4de3-8f56-e18072f17a45")
                    },
                    value,
                    this._StrongType.Nullify.ApprovedCount);
            }
        }


        private string BestTimetoCallFrom
        {
            get
            {
                return ((string)(base.GetMemberValue("Best Time to Call From")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Best Time to Call From",
                        Id = new Guid("606cd02c-360b-432e-9972-dedddd082a30")
                    },
                    value,
                    this._StrongType.Nullify.BestTimetoCallFrom);
            }
        }


        private string BestTimetoCallTo
        {
            get
            {
                return ((string)(base.GetMemberValue("Best Time to Call To")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Best Time to Call To",
                        Id = new Guid("b740b33a-d464-4da0-a501-546ff6c86a2f")
                    },
                    value,
                    this._StrongType.Nullify.BestTimetoCallTo);
            }
        }


        private MemberIdentifier BillingCurrency
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("BillingCurrency")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "BillingCurrency",
                        Id = new Guid("02b51f96-c32b-46f3-8a47-3427c62648dd")
                    },
                    value,
                    this._StrongType.Nullify.BillingCurrency);
            }
        }


        private string CarrierRoute
        {
            get
            {
                return ((string)(base.GetMemberValue("Carrier Route")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Carrier Route",
                        Id = new Guid("dd2d9a33-8671-45d1-9d5e-44f620f58ded")
                    },
                    value,
                    this._StrongType.Nullify.CarrierRoute);
            }
        }


        private string CBSACode
        {
            get
            {
                return ((string)(base.GetMemberValue("CBSA Code")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "CBSA Code",
                        Id = new Guid("596a0e1b-43ae-48d7-b459-6e4d489506bf")
                    },
                    value,
                    this._StrongType.Nullify.CBSACode);
            }
        }


        private string CBSADivisionCode
        {
            get
            {
                return ((string)(base.GetMemberValue("CBSA Division Code")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "CBSA Division Code",
                        Id = new Guid("9dcc73aa-c412-40ef-8de6-8ac8fef592ca")
                    },
                    value,
                    this._StrongType.Nullify.CBSADivisionCode);
            }
        }


        private string CBSADivisionLevel
        {
            get
            {
                return ((string)(base.GetMemberValue("CBSA Division Level")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "CBSA Division Level",
                        Id = new Guid("03095828-49a6-4b75-b3e2-1b50cf1ffecf")
                    },
                    value,
                    this._StrongType.Nullify.CBSADivisionLevel);
            }
        }


        private string CBSADivisionTitle
        {
            get
            {
                return ((string)(base.GetMemberValue("CBSA Division Title")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "CBSA Division Title",
                        Id = new Guid("1f5f0e27-fbea-4415-a646-bac2298f543f")
                    },
                    value,
                    this._StrongType.Nullify.CBSADivisionTitle);
            }
        }


        private string CBSALevel
        {
            get
            {
                return ((string)(base.GetMemberValue("CBSA Level")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "CBSA Level",
                        Id = new Guid("a3c5abf3-1197-4a1a-adb7-ec6b4c076a70")
                    },
                    value,
                    this._StrongType.Nullify.CBSALevel);
            }
        }


        private string CBSATitle
        {
            get
            {
                return ((string)(base.GetMemberValue("CBSA Title")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "CBSA Title",
                        Id = new Guid("b3050575-2453-44a0-835e-aa4466405dcb")
                    },
                    value,
                    this._StrongType.Nullify.CBSATitle);
            }
        }


        private string CensusBlock
        {
            get
            {
                return ((string)(base.GetMemberValue("Census Block")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Census Block",
                        Id = new Guid("9b52798f-07d9-44f8-82a3-347c62fbd757")
                    },
                    value,
                    this._StrongType.Nullify.CensusBlock);
            }
        }


        private string CensusTract
        {
            get
            {
                return ((string)(base.GetMemberValue("Census Tract")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Census Tract",
                        Id = new Guid("d4fae1f6-7cff-4c40-b1b1-58a75cd7ab2b")
                    },
                    value,
                    this._StrongType.Nullify.CensusTract);
            }
        }


        private string City
        {
            get
            {
                return ((string)(base.GetMemberValue("City")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "City",
                        Id = new Guid("f29df8ed-ca21-43de-9663-2aeefad34780")
                    },
                    value,
                    this._StrongType.Nullify.City);
            }
        }


        private string Comment
        {
            get
            {
                return ((string)(base.GetMemberValue("Comment")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Comment",
                        Id = new Guid("86f49be3-adfd-4c1a-88cc-2d8ec80ed753")
                    },
                    value,
                    this._StrongType.Nullify.Comment);
            }
        }


        private string ContactFullName
        {
            get
            {
                return ((string)(base.GetMemberValue("ContactFullName")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "ContactFullName",
                        Id = new Guid("911fe1b0-36d6-4286-b402-e1acd5602fe2")
                    },
                    value,
                    this._StrongType.Nullify.ContactFullName);
            }
        }


        private string Country
        {
            get
            {
                return ((string)(base.GetMemberValue("Country")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Country",
                        Id = new Guid("8ae46e69-bff2-42cd-858f-6bea5fd7ed7e")
                    },
                    value,
                    this._StrongType.Nullify.Country);
            }
        }


        private string CountyFIPS
        {
            get
            {
                return ((string)(base.GetMemberValue("County FIPS")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "County FIPS",
                        Id = new Guid("5ea8079e-25e8-42a9-85d9-80378afec486")
                    },
                    value,
                    this._StrongType.Nullify.CountyFIPS);
            }
        }


        private string CountyName
        {
            get
            {
                return ((string)(base.GetMemberValue("County Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "County Name",
                        Id = new Guid("506cc8ab-f42b-438b-80e4-77f4481ed7b2")
                    },
                    value,
                    this._StrongType.Nullify.CountyName);
            }
        }


        private Nullable<double> CreditLimit
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("Credit Limit")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Credit Limit",
                        Id = new Guid("747de307-f218-454c-b8ba-1e1103aaf9ee")
                    },
                    value,
                    this._StrongType.Nullify.CreditLimit);
            }
        }


        private MemberIdentifier CustomerStatus
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("CustomerStatus")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "CustomerStatus",
                        Id = new Guid("4d6672f3-a3c2-4c45-b776-111dd765ff8b")
                    },
                    value,
                    this._StrongType.Nullify.CustomerStatus);
            }
        }


        private string DeliveryPointCheckDigit
        {
            get
            {
                return ((string)(base.GetMemberValue("Delivery Point Check Digit")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Delivery Point Check Digit",
                        Id = new Guid("94c9a0d8-0ac2-486b-95c7-b3720afda487")
                    },
                    value,
                    this._StrongType.Nullify.DeliveryPointCheckDigit);
            }
        }


        private string DeliveryPointCode
        {
            get
            {
                return ((string)(base.GetMemberValue("Delivery Point Code")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Delivery Point Code",
                        Id = new Guid("e54c1901-afb0-47c5-9682-5a04b0d3daeb")
                    },
                    value,
                    this._StrongType.Nullify.DeliveryPointCode);
            }
        }


        private MemberIdentifier DoNotEmail
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("DoNotEmail")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "DoNotEmail",
                        Id = new Guid("5d193ca1-81cf-4327-851b-e64a4b54d2d0")
                    },
                    value,
                    this._StrongType.Nullify.DoNotEmail);
            }
        }


        private MemberIdentifier DoNotFax
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("DoNotFax")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "DoNotFax",
                        Id = new Guid("0be20872-5c38-442b-bcbb-7e8b67cb9888")
                    },
                    value,
                    this._StrongType.Nullify.DoNotFax);
            }
        }


        private MemberIdentifier DoNotPhone
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("DoNotPhone")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "DoNotPhone",
                        Id = new Guid("37168878-bd06-4b5c-b68f-c92390733672")
                    },
                    value,
                    this._StrongType.Nullify.DoNotPhone);
            }
        }


        private string DynamicsCRMID
        {
            get
            {
                return ((string)(base.GetMemberValue("DynamicsCRMID")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "DynamicsCRMID",
                        Id = new Guid("969e8eee-472b-402a-80d3-67b626727717")
                    },
                    value,
                    this._StrongType.Nullify.DynamicsCRMID);
            }
        }


        private string EmailVerificationResults
        {
            get
            {
                return ((string)(base.GetMemberValue("Email Verification Results")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Email Verification Results",
                        Id = new Guid("b56ffdf0-f4df-442e-943b-a53f6fda6fef")
                    },
                    value,
                    this._StrongType.Nullify.EmailVerificationResults);
            }
        }


        private MemberIdentifier EmailVerificationStatus
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Email Verification Status")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Email Verification Status",
                        Id = new Guid("d9049295-fefc-4f21-a880-104d0bd58b20")
                    },
                    value,
                    this._StrongType.Nullify.EmailVerificationStatus);
            }
        }


        private string EmailAddress
        {
            get
            {
                return ((string)(base.GetMemberValue("EmailAddress")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "EmailAddress",
                        Id = new Guid("2735d9ef-4885-4a8f-9026-75d91b796cb8")
                    },
                    value,
                    this._StrongType.Nullify.EmailAddress);
            }
        }


        private string FirstName
        {
            get
            {
                return ((string)(base.GetMemberValue("First Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "First Name",
                        Id = new Guid("195edc4d-b42c-4812-b75c-b9c1f5ac7566")
                    },
                    value,
                    this._StrongType.Nullify.FirstName);
            }
        }


        private string FullName
        {
            get
            {
                return ((string)(base.GetMemberValue("Full Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Full Name",
                        Id = new Guid("c32cbc5a-992c-4ba3-b95c-ba228f1d9828")
                    },
                    value,
                    this._StrongType.Nullify.FullName);
            }
        }


        private string FullAddress
        {
            get
            {
                return ((string)(base.GetMemberValue("FullAddress")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "FullAddress",
                        Id = new Guid("67d2cf35-307e-4fcd-b809-b23f442bea3b")
                    },
                    value,
                    this._StrongType.Nullify.FullAddress);
            }
        }


        private string GoogleMapsLink
        {
            get
            {
                return ((string)(base.GetMemberValue("GoogleMapsLink")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "GoogleMapsLink",
                        Id = new Guid("98bd421d-167e-4757-a9fb-1758fc5b7733")
                    },
                    value,
                    this._StrongType.Nullify.GoogleMapsLink);
            }
        }


        private MemberIdentifier Industry
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Industry")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Industry",
                        Id = new Guid("a9a5a79d-3648-4a6d-8615-90645a9605de")
                    },
                    value,
                    this._StrongType.Nullify.Industry);
            }
        }


        private string LastName
        {
            get
            {
                return ((string)(base.GetMemberValue("Last Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Last Name",
                        Id = new Guid("9d2375b0-4530-4e99-a671-0dc5605f2389")
                    },
                    value,
                    this._StrongType.Nullify.LastName);
            }
        }


        private Nullable<double> LastMonthSales
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("LastMonthSales")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "LastMonthSales",
                        Id = new Guid("c558a040-f96c-4407-b75f-39a7a22c7ac6")
                    },
                    value,
                    this._StrongType.Nullify.LastMonthSales);
            }
        }


        private Nullable<double> Latitude
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("Latitude")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Latitude",
                        Id = new Guid("31b12f7e-8804-4a7d-8f22-95725b2ab6eb")
                    },
                    value,
                    this._StrongType.Nullify.Latitude);
            }
        }


        private string LiveStatus
        {
            get
            {
                return ((string)(base.GetMemberValue("Live Status")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Live Status",
                        Id = new Guid("4c42c3bb-85f5-438d-a19d-bc9d93120a28")
                    },
                    value,
                    this._StrongType.Nullify.LiveStatus);
            }
        }


        private MemberIdentifier LocationConfidence
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Location Confidence")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Location Confidence",
                        Id = new Guid("6bf157ad-25ec-42df-99a8-44b89f6e2266")
                    },
                    value,
                    this._StrongType.Nullify.LocationConfidence);
            }
        }


        private Nullable<double> LocationResponseCount
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("Location Response Count")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Location Response Count",
                        Id = new Guid("d26ee6df-b459-41bb-bbd9-0caf3eef29d3")
                    },
                    value,
                    this._StrongType.Nullify.LocationResponseCount);
            }
        }


        private MemberIdentifier LocationVerificationStatus
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Location Verification Status")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Location Verification Status",
                        Id = new Guid("b3d1e657-8ae9-4fb2-86c4-424bf185c9a7")
                    },
                    value,
                    this._StrongType.Nullify.LocationVerificationStatus);
            }
        }


        private Nullable<double> Longitude
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("Longitude")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Longitude",
                        Id = new Guid("76ba26ba-a936-4cc6-a08c-f91354956358")
                    },
                    value,
                    this._StrongType.Nullify.Longitude);
            }
        }


        private Nullable<double> MatchScore
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("Match Score")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Match Score",
                        Id = new Guid("18222b28-4f2d-4dd3-96e7-de8ebce9c34b")
                    },
                    value,
                    this._StrongType.Nullify.MatchScore);
            }
        }


        private string MiddleName
        {
            get
            {
                return ((string)(base.GetMemberValue("Middle Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Middle Name",
                        Id = new Guid("5a61e234-0c29-40f7-b08b-b6db4ec5d6c8")
                    },
                    value,
                    this._StrongType.Nullify.MiddleName);
            }
        }


        private string NameParsingResults
        {
            get
            {
                return ((string)(base.GetMemberValue("Name Parsing Results")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Name Parsing Results",
                        Id = new Guid("ac1bb703-ebb4-4592-b47c-8464186f0356")
                    },
                    value,
                    this._StrongType.Nullify.NameParsingResults);
            }
        }


        private MemberIdentifier NameParsingStatus
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Name Parsing Status")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Name Parsing Status",
                        Id = new Guid("e3e7beea-1fc6-452e-aab8-dd8b69763902")
                    },
                    value,
                    this._StrongType.Nullify.NameParsingStatus);
            }
        }


        private MemberIdentifier PartyType
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("PartyType")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "PartyType",
                        Id = new Guid("6eb2ee9d-84a3-4ef2-bddb-fe1a641eb270")
                    },
                    value,
                    this._StrongType.Nullify.PartyType);
            }
        }


        private MemberIdentifier PaymentTerms
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("PaymentTerms")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "PaymentTerms",
                        Id = new Guid("e7b9288b-76f5-4854-880b-b373289e3b83")
                    },
                    value,
                    this._StrongType.Nullify.PaymentTerms);
            }
        }


        private string PhoneNumber
        {
            get
            {
                return ((string)(base.GetMemberValue("Phone Number")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Phone Number",
                        Id = new Guid("292132fb-66e1-41a4-99b6-89b719e05545")
                    },
                    value,
                    this._StrongType.Nullify.PhoneNumber);
            }
        }


        private string PhoneVerificationResults
        {
            get
            {
                return ((string)(base.GetMemberValue("Phone Verification Results")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Phone Verification Results",
                        Id = new Guid("442c0aa1-d86f-4e9e-bef7-1981cf187935")
                    },
                    value,
                    this._StrongType.Nullify.PhoneVerificationResults);
            }
        }


        private MemberIdentifier PhoneVerificationStatus
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Phone Verification Status")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Phone Verification Status",
                        Id = new Guid("a30958fc-050c-4115-af87-c3e72576e9d0")
                    },
                    value,
                    this._StrongType.Nullify.PhoneVerificationStatus);
            }
        }


        private string PlaceCode
        {
            get
            {
                return ((string)(base.GetMemberValue("Place Code")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Place Code",
                        Id = new Guid("7d772667-3550-4359-99e4-4212e7e240fc")
                    },
                    value,
                    this._StrongType.Nullify.PlaceCode);
            }
        }


        private string PlaceName
        {
            get
            {
                return ((string)(base.GetMemberValue("Place Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Place Name",
                        Id = new Guid("273a179b-4442-4020-b0ca-e284a8c3e9e4")
                    },
                    value,
                    this._StrongType.Nullify.PlaceName);
            }
        }


        private string Plus4
        {
            get
            {
                return ((string)(base.GetMemberValue("Plus4")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Plus4",
                        Id = new Guid("1dc537c5-34e0-4da1-960b-eee8d5942d4d")
                    },
                    value,
                    this._StrongType.Nullify.Plus4);
            }
        }


        private string PMBName
        {
            get
            {
                return ((string)(base.GetMemberValue("PMB Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "PMB Name",
                        Id = new Guid("cce65d84-61c3-445c-bf5f-3ba95288e610")
                    },
                    value,
                    this._StrongType.Nullify.PMBName);
            }
        }


        private string PMBNumber
        {
            get
            {
                return ((string)(base.GetMemberValue("PMB Number")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "PMB Number",
                        Id = new Guid("d1b24901-1323-41ac-a659-348c0429d94d")
                    },
                    value,
                    this._StrongType.Nullify.PMBNumber);
            }
        }


        private string PostDirection
        {
            get
            {
                return ((string)(base.GetMemberValue("Post Direction")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Post Direction",
                        Id = new Guid("f7cb81f5-ff62-4823-a365-6d1980e6e5b6")
                    },
                    value,
                    this._StrongType.Nullify.PostDirection);
            }
        }


        private string PostalCode
        {
            get
            {
                return ((string)(base.GetMemberValue("Postal Code")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Postal Code",
                        Id = new Guid("fe5974d7-e94e-4489-be3e-2fb32a68eb11")
                    },
                    value,
                    this._StrongType.Nullify.PostalCode);
            }
        }


        private string PreDirection
        {
            get
            {
                return ((string)(base.GetMemberValue("Pre Direction")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Pre Direction",
                        Id = new Guid("f05d1fde-7bbe-4840-ba82-07c571881958")
                    },
                    value,
                    this._StrongType.Nullify.PreDirection);
            }
        }


        private MemberIdentifier PreferredCommunication
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Preferred Communication")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Preferred Communication",
                        Id = new Guid("f3455b2e-8ac6-4bf8-a271-0edcd2797c55")
                    },
                    value,
                    this._StrongType.Nullify.PreferredCommunication);
            }
        }


        private Nullable<double> ProposedCount
        {
            get
            {
                return ((Nullable<double>)(base.GetMemberValue("Proposed Count")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Proposed Count",
                        Id = new Guid("fd4bf09c-c181-48fb-9eab-815a635dc1e3")
                    },
                    value,
                    this._StrongType.Nullify.ProposedCount);
            }
        }


        private MemberIdentifier Region
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Region")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Region",
                        Id = new Guid("88bc0d7b-123e-4b0b-a4d0-b2bc4a336492")
                    },
                    value,
                    this._StrongType.Nullify.Region);
            }
        }


        private string RejectionReason
        {
            get
            {
                return ((string)(base.GetMemberValue("Rejection Reason")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Rejection Reason",
                        Id = new Guid("ffbcd6aa-0bf4-4047-ac49-003eefad1d14")
                    },
                    value,
                    this._StrongType.Nullify.RejectionReason);
            }
        }


        private string SalesforceID
        {
            get
            {
                return ((string)(base.GetMemberValue("SalesforceID")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "SalesforceID",
                        Id = new Guid("5fd1959e-f5eb-4880-94e8-da6566946bff")
                    },
                    value,
                    this._StrongType.Nullify.SalesforceID);
            }
        }


        private MemberIdentifier SourceSystem
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("SourceSystem")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "SourceSystem",
                        Id = new Guid("84e53bc0-f6ec-419a-8567-b9926221f982")
                    },
                    value,
                    this._StrongType.Nullify.SourceSystem);
            }
        }


        private string StateProvince
        {
            get
            {
                return ((string)(base.GetMemberValue("StateProvince")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "StateProvince",
                        Id = new Guid("5b2a058e-bccf-4e03-9381-307934a38fbd")
                    },
                    value,
                    this._StrongType.Nullify.StateProvince);
            }
        }


        private MemberIdentifier Status
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Status")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Status",
                        Id = new Guid("9ad14714-a4b3-4147-bcd6-b53a2357ff92")
                    },
                    value,
                    this._StrongType.Nullify.Status);
            }
        }


        private string StreetName
        {
            get
            {
                return ((string)(base.GetMemberValue("Street Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Street Name",
                        Id = new Guid("907e6249-6505-4fe4-841e-2ca4de136758")
                    },
                    value,
                    this._StrongType.Nullify.StreetName);
            }
        }


        private string StreetNumber
        {
            get
            {
                return ((string)(base.GetMemberValue("Street Number")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Street Number",
                        Id = new Guid("44e6da62-9198-4f11-97f5-1d9966557ca1")
                    },
                    value,
                    this._StrongType.Nullify.StreetNumber);
            }
        }


        private string StreetSuffix
        {
            get
            {
                return ((string)(base.GetMemberValue("Street Suffix")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Street Suffix",
                        Id = new Guid("2c942f85-675c-4ebf-b0b6-e0fa6fe842b8")
                    },
                    value,
                    this._StrongType.Nullify.StreetSuffix);
            }
        }


        private string SuiteName
        {
            get
            {
                return ((string)(base.GetMemberValue("Suite Name")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Suite Name",
                        Id = new Guid("b013a5be-581c-42e2-9bcc-2886dd14382c")
                    },
                    value,
                    this._StrongType.Nullify.SuiteName);
            }
        }


        private string SuiteNumber
        {
            get
            {
                return ((string)(base.GetMemberValue("Suite Number")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Suite Number",
                        Id = new Guid("8234f872-2ebc-4e7b-a81c-c58a727360db")
                    },
                    value,
                    this._StrongType.Nullify.SuiteNumber);
            }
        }


        private string TaxID
        {
            get
            {
                return ((string)(base.GetMemberValue("TaxID")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "TaxID",
                        Id = new Guid("f3a7872c-044b-47c1-b604-cdc71c3300d4")
                    },
                    value,
                    this._StrongType.Nullify.TaxID);
            }
        }


        private MemberIdentifier ValidationAction
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("Validation Action")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "Validation Action",
                        Id = new Guid("f25198fe-95f3-40a5-bce0-575d7342e39a")
                    },
                    value,
                    this._StrongType.Nullify.ValidationAction);
            }
        }


        private MemberIdentifier WorkflowStatus
        {
            get
            {
                return ((MemberIdentifier)(base.GetMemberValue("WorkflowStatus")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "WorkflowStatus",
                        Id = new Guid("8ad96d18-7dee-4b0e-ae02-d27adc499497")
                    },
                    value,
                    this._StrongType.Nullify.WorkflowStatus);
            }
        }


        private string ZIPType
        {
            get
            {
                return ((string)(base.GetMemberValue("ZIP Type")));
            }
            set
            {
                base.SetMemberValue(
                    new Identifier
                    {
                        Name = "ZIP Type",
                        Id = new Guid("49b0a1a8-2bf7-4ec1-b79e-c62f06af2df5")
                    },
                    value,
                    this._StrongType.Nullify.ZIPType);
            }
        }


        protected override BaseMemberType Transform(Member internalMember)
        {
            _StrongType = new CustomerMember();
            base.Transform(_StrongType, internalMember);

            _StrongType.AddressKey = this.AddressKey;


            _StrongType.AddressLine1 = this.AddressLine1;


            _StrongType.AddressLine2 = this.AddressLine2;


            _StrongType.AddressLookupStatus = this.AddressLookupStatus;


            _StrongType.AddressType = this.AddressType;


            _StrongType.ApprovedCount = this.ApprovedCount;


            _StrongType.BestTimetoCallFrom = this.BestTimetoCallFrom;


            _StrongType.BestTimetoCallTo = this.BestTimetoCallTo;


            _StrongType.BillingCurrency = this.BillingCurrency;


            _StrongType.CarrierRoute = this.CarrierRoute;


            _StrongType.CBSACode = this.CBSACode;


            _StrongType.CBSADivisionCode = this.CBSADivisionCode;


            _StrongType.CBSADivisionLevel = this.CBSADivisionLevel;


            _StrongType.CBSADivisionTitle = this.CBSADivisionTitle;


            _StrongType.CBSALevel = this.CBSALevel;


            _StrongType.CBSATitle = this.CBSATitle;


            _StrongType.CensusBlock = this.CensusBlock;


            _StrongType.CensusTract = this.CensusTract;


            _StrongType.City = this.City;


            _StrongType.Comment = this.Comment;


            _StrongType.ContactFullName = this.ContactFullName;


            _StrongType.Country = this.Country;


            _StrongType.CountyFIPS = this.CountyFIPS;


            _StrongType.CountyName = this.CountyName;


            _StrongType.CreditLimit = this.CreditLimit;


            _StrongType.CustomerStatus = this.CustomerStatus;


            _StrongType.DeliveryPointCheckDigit = this.DeliveryPointCheckDigit;


            _StrongType.DeliveryPointCode = this.DeliveryPointCode;


            _StrongType.DoNotEmail = this.DoNotEmail;


            _StrongType.DoNotFax = this.DoNotFax;


            _StrongType.DoNotPhone = this.DoNotPhone;


            _StrongType.DynamicsCRMID = this.DynamicsCRMID;


            _StrongType.EmailVerificationResults = this.EmailVerificationResults;


            _StrongType.EmailVerificationStatus = this.EmailVerificationStatus;


            _StrongType.EmailAddress = this.EmailAddress;


            _StrongType.FirstName = this.FirstName;


            _StrongType.FullName = this.FullName;


            _StrongType.FullAddress = this.FullAddress;


            _StrongType.GoogleMapsLink = this.GoogleMapsLink;


            _StrongType.Industry = this.Industry;


            _StrongType.LastName = this.LastName;


            _StrongType.LastMonthSales = this.LastMonthSales;


            _StrongType.Latitude = this.Latitude;


            _StrongType.LiveStatus = this.LiveStatus;


            _StrongType.LocationConfidence = this.LocationConfidence;


            _StrongType.LocationResponseCount = this.LocationResponseCount;


            _StrongType.LocationVerificationStatus = this.LocationVerificationStatus;


            _StrongType.Longitude = this.Longitude;


            _StrongType.MatchScore = this.MatchScore;


            _StrongType.MiddleName = this.MiddleName;


            _StrongType.NameParsingResults = this.NameParsingResults;


            _StrongType.NameParsingStatus = this.NameParsingStatus;


            _StrongType.PartyType = this.PartyType;


            _StrongType.PaymentTerms = this.PaymentTerms;


            _StrongType.PhoneNumber = this.PhoneNumber;


            _StrongType.PhoneVerificationResults = this.PhoneVerificationResults;


            _StrongType.PhoneVerificationStatus = this.PhoneVerificationStatus;


            _StrongType.PlaceCode = this.PlaceCode;


            _StrongType.PlaceName = this.PlaceName;


            _StrongType.Plus4 = this.Plus4;


            _StrongType.PMBName = this.PMBName;


            _StrongType.PMBNumber = this.PMBNumber;


            _StrongType.PostDirection = this.PostDirection;


            _StrongType.PostalCode = this.PostalCode;


            _StrongType.PreDirection = this.PreDirection;


            _StrongType.PreferredCommunication = this.PreferredCommunication;


            _StrongType.ProposedCount = this.ProposedCount;


            _StrongType.Region = this.Region;


            _StrongType.RejectionReason = this.RejectionReason;


            _StrongType.SalesforceID = this.SalesforceID;


            _StrongType.SourceSystem = this.SourceSystem;


            _StrongType.StateProvince = this.StateProvince;


            _StrongType.Status = this.Status;


            _StrongType.StreetName = this.StreetName;


            _StrongType.StreetNumber = this.StreetNumber;


            _StrongType.StreetSuffix = this.StreetSuffix;


            _StrongType.SuiteName = this.SuiteName;


            _StrongType.SuiteNumber = this.SuiteNumber;


            _StrongType.TaxID = this.TaxID;


            _StrongType.ValidationAction = this.ValidationAction;


            _StrongType.WorkflowStatus = this.WorkflowStatus;


            _StrongType.ZIPType = this.ZIPType;


            return _StrongType;
        }

        protected override Member Transform(BaseMemberType externalMember)
        {
            Member internalMember;
            internalMember = base.Transform(externalMember);
            _StrongType = ((CustomerMember)(externalMember));
            if ((this._StrongType.Nullify == null))
            {
                this._StrongType.Nullify = new CustomerMember.NullificationMask();
            }

            this.AddressKey = _StrongType.AddressKey;


            this.AddressLine1 = _StrongType.AddressLine1;


            this.AddressLine2 = _StrongType.AddressLine2;


            this.AddressLookupStatus = _StrongType.AddressLookupStatus;


            this.AddressType = _StrongType.AddressType;


            this.ApprovedCount = _StrongType.ApprovedCount;


            this.BestTimetoCallFrom = _StrongType.BestTimetoCallFrom;


            this.BestTimetoCallTo = _StrongType.BestTimetoCallTo;


            this.BillingCurrency = _StrongType.BillingCurrency;


            this.CarrierRoute = _StrongType.CarrierRoute;


            this.CBSACode = _StrongType.CBSACode;


            this.CBSADivisionCode = _StrongType.CBSADivisionCode;


            this.CBSADivisionLevel = _StrongType.CBSADivisionLevel;


            this.CBSADivisionTitle = _StrongType.CBSADivisionTitle;


            this.CBSALevel = _StrongType.CBSALevel;


            this.CBSATitle = _StrongType.CBSATitle;


            this.CensusBlock = _StrongType.CensusBlock;


            this.CensusTract = _StrongType.CensusTract;


            this.City = _StrongType.City;


            this.Comment = _StrongType.Comment;


            this.ContactFullName = _StrongType.ContactFullName;


            this.Country = _StrongType.Country;


            this.CountyFIPS = _StrongType.CountyFIPS;


            this.CountyName = _StrongType.CountyName;


            this.CreditLimit = _StrongType.CreditLimit;


            this.CustomerStatus = _StrongType.CustomerStatus;


            this.DeliveryPointCheckDigit = _StrongType.DeliveryPointCheckDigit;


            this.DeliveryPointCode = _StrongType.DeliveryPointCode;


            this.DoNotEmail = _StrongType.DoNotEmail;


            this.DoNotFax = _StrongType.DoNotFax;


            this.DoNotPhone = _StrongType.DoNotPhone;


            this.DynamicsCRMID = _StrongType.DynamicsCRMID;


            this.EmailVerificationResults = _StrongType.EmailVerificationResults;


            this.EmailVerificationStatus = _StrongType.EmailVerificationStatus;


            this.EmailAddress = _StrongType.EmailAddress;


            this.FirstName = _StrongType.FirstName;


            this.FullName = _StrongType.FullName;


            this.FullAddress = _StrongType.FullAddress;


            this.GoogleMapsLink = _StrongType.GoogleMapsLink;


            this.Industry = _StrongType.Industry;


            this.LastName = _StrongType.LastName;


            this.LastMonthSales = _StrongType.LastMonthSales;


            this.Latitude = _StrongType.Latitude;


            this.LiveStatus = _StrongType.LiveStatus;


            this.LocationConfidence = _StrongType.LocationConfidence;


            this.LocationResponseCount = _StrongType.LocationResponseCount;


            this.LocationVerificationStatus = _StrongType.LocationVerificationStatus;


            this.Longitude = _StrongType.Longitude;


            this.MatchScore = _StrongType.MatchScore;


            this.MiddleName = _StrongType.MiddleName;


            this.NameParsingResults = _StrongType.NameParsingResults;


            this.NameParsingStatus = _StrongType.NameParsingStatus;


            this.PartyType = _StrongType.PartyType;


            this.PaymentTerms = _StrongType.PaymentTerms;


            this.PhoneNumber = _StrongType.PhoneNumber;


            this.PhoneVerificationResults = _StrongType.PhoneVerificationResults;


            this.PhoneVerificationStatus = _StrongType.PhoneVerificationStatus;


            this.PlaceCode = _StrongType.PlaceCode;


            this.PlaceName = _StrongType.PlaceName;


            this.Plus4 = _StrongType.Plus4;


            this.PMBName = _StrongType.PMBName;


            this.PMBNumber = _StrongType.PMBNumber;


            this.PostDirection = _StrongType.PostDirection;


            this.PostalCode = _StrongType.PostalCode;


            this.PreDirection = _StrongType.PreDirection;


            this.PreferredCommunication = _StrongType.PreferredCommunication;


            this.ProposedCount = _StrongType.ProposedCount;


            this.Region = _StrongType.Region;


            this.RejectionReason = _StrongType.RejectionReason;


            this.SalesforceID = _StrongType.SalesforceID;


            this.SourceSystem = _StrongType.SourceSystem;


            this.StateProvince = _StrongType.StateProvince;


            this.Status = _StrongType.Status;


            this.StreetName = _StrongType.StreetName;


            this.StreetNumber = _StrongType.StreetNumber;


            this.StreetSuffix = _StrongType.StreetSuffix;


            this.SuiteName = _StrongType.SuiteName;


            this.SuiteNumber = _StrongType.SuiteNumber;


            this.TaxID = _StrongType.TaxID;


            this.ValidationAction = _StrongType.ValidationAction;


            this.WorkflowStatus = _StrongType.WorkflowStatus;


            this.ZIPType = _StrongType.ZIPType;


            return internalMember;
        }
    }
}
