
using Profisee.MasterDataMaestro.Services.DataContracts;
using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
using Profisee.Services.Sdk.AcceleratorFramework;
using Profisee.Services.Sdk.Common.Contracts.DataContext;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Web.Services.Description;
using Mdm.Profisee_Customer360Service.ServiceLibrary.MemberAdapters;
using Mdm.Profisee_Customer360Service.Contracts.MemberDataContracts;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Maestro SDK Web Services Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mdm.Profisee_Customer360Service.ServiceLibrary
{
    using Mdm.Profisee_Customer360Service.Contracts;
    using Mdm.Profisee_Customer360Service.Contracts.MemberDataContracts;
    using Mdm.Profisee_Customer360Service.ServiceLibrary.MemberAdapters;
    using Profisee.MasterDataMaestro.Services.DataContracts;
    using Profisee.MasterDataMaestro.Services.DataContracts.MasterDataServices;
    using Profisee.Services.Sdk.AcceleratorFramework;
    using Profisee.Services.Sdk.Common.Contracts.DataContext;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class LookupBeforeCreate : BaseModelService, ILookupBeforeCreate
    {
		private const String CustomerEntityName = "B2B_Customer";

		private static Identifier CustomerEntityId = new Identifier { Name = CustomerEntityName, Id = new Guid("3fed5f55-8bd4-4b34-8c92-d17cadb16792") };

		private MdmEntity<CustomerMember,CustomerMemberAdapter> CustomerEntity = null;

		private Collection<Identifier> CustomerAttributes = new Collection<Identifier> 
		{
			new Identifier { Name = "Name", Id = new Guid("02fb5700-d44a-45b7-8c70-c60a7099d9fa") },
			new Identifier { Name = "Code", Id = new Guid("82379b63-a2e6-4211-b4c3-952c217eef21") },
			new Identifier { Name = "Address Key", Id = new Guid("423ac104-1db2-403b-a832-0f33f70b0684") },
			new Identifier { Name = "Address Line 1", Id = new Guid("dd953704-b0ab-43fd-942b-6994c2fe365a") },
			new Identifier { Name = "Address Line 2", Id = new Guid("acf1cd3f-b1b3-428a-953c-92a203874073") },
			new Identifier { Name = "Address Lookup Status", Id = new Guid("c165b926-a560-41c4-a63a-df568dacf9ab") },
			new Identifier { Name = "Address Type", Id = new Guid("dd429b21-f56c-4713-ac50-325eff3bbb45") },
			new Identifier { Name = "Approved Count", Id = new Guid("f768df27-de9d-4de3-8f56-e18072f17a45") },
			new Identifier { Name = "Best Time to Call From", Id = new Guid("606cd02c-360b-432e-9972-dedddd082a30") },
			new Identifier { Name = "Best Time to Call To", Id = new Guid("b740b33a-d464-4da0-a501-546ff6c86a2f") },
			new Identifier { Name = "BillingCurrency", Id = new Guid("02b51f96-c32b-46f3-8a47-3427c62648dd") },
			new Identifier { Name = "Carrier Route", Id = new Guid("dd2d9a33-8671-45d1-9d5e-44f620f58ded") },
			new Identifier { Name = "CBSA Code", Id = new Guid("596a0e1b-43ae-48d7-b459-6e4d489506bf") },
			new Identifier { Name = "CBSA Division Code", Id = new Guid("9dcc73aa-c412-40ef-8de6-8ac8fef592ca") },
			new Identifier { Name = "CBSA Division Level", Id = new Guid("03095828-49a6-4b75-b3e2-1b50cf1ffecf") },
			new Identifier { Name = "CBSA Division Title", Id = new Guid("1f5f0e27-fbea-4415-a646-bac2298f543f") },
			new Identifier { Name = "CBSA Level", Id = new Guid("a3c5abf3-1197-4a1a-adb7-ec6b4c076a70") },
			new Identifier { Name = "CBSA Title", Id = new Guid("b3050575-2453-44a0-835e-aa4466405dcb") },
			new Identifier { Name = "Census Block", Id = new Guid("9b52798f-07d9-44f8-82a3-347c62fbd757") },
			new Identifier { Name = "Census Tract", Id = new Guid("d4fae1f6-7cff-4c40-b1b1-58a75cd7ab2b") },
			new Identifier { Name = "City", Id = new Guid("f29df8ed-ca21-43de-9663-2aeefad34780") },
			new Identifier { Name = "Comment", Id = new Guid("86f49be3-adfd-4c1a-88cc-2d8ec80ed753") },
			new Identifier { Name = "ContactFullName", Id = new Guid("911fe1b0-36d6-4286-b402-e1acd5602fe2") },
			new Identifier { Name = "Country", Id = new Guid("8ae46e69-bff2-42cd-858f-6bea5fd7ed7e") },
			new Identifier { Name = "County FIPS", Id = new Guid("5ea8079e-25e8-42a9-85d9-80378afec486") },
			new Identifier { Name = "County Name", Id = new Guid("506cc8ab-f42b-438b-80e4-77f4481ed7b2") },
			new Identifier { Name = "Credit Limit", Id = new Guid("747de307-f218-454c-b8ba-1e1103aaf9ee") },
			new Identifier { Name = "CustomerStatus", Id = new Guid("4d6672f3-a3c2-4c45-b776-111dd765ff8b") },
			new Identifier { Name = "Delivery Point Check Digit", Id = new Guid("94c9a0d8-0ac2-486b-95c7-b3720afda487") },
			new Identifier { Name = "Delivery Point Code", Id = new Guid("e54c1901-afb0-47c5-9682-5a04b0d3daeb") },
			new Identifier { Name = "DoNotEmail", Id = new Guid("5d193ca1-81cf-4327-851b-e64a4b54d2d0") },
			new Identifier { Name = "DoNotFax", Id = new Guid("0be20872-5c38-442b-bcbb-7e8b67cb9888") },
			new Identifier { Name = "DoNotPhone", Id = new Guid("37168878-bd06-4b5c-b68f-c92390733672") },
			new Identifier { Name = "DynamicsCRMID", Id = new Guid("969e8eee-472b-402a-80d3-67b626727717") },
			new Identifier { Name = "Email Verification Results", Id = new Guid("b56ffdf0-f4df-442e-943b-a53f6fda6fef") },
			new Identifier { Name = "Email Verification Status", Id = new Guid("d9049295-fefc-4f21-a880-104d0bd58b20") },
			new Identifier { Name = "EmailAddress", Id = new Guid("2735d9ef-4885-4a8f-9026-75d91b796cb8") },
			new Identifier { Name = "First Name", Id = new Guid("195edc4d-b42c-4812-b75c-b9c1f5ac7566") },
			new Identifier { Name = "Full Name", Id = new Guid("c32cbc5a-992c-4ba3-b95c-ba228f1d9828") },
			new Identifier { Name = "FullAddress", Id = new Guid("67d2cf35-307e-4fcd-b809-b23f442bea3b") },
			new Identifier { Name = "GoogleMapsLink", Id = new Guid("98bd421d-167e-4757-a9fb-1758fc5b7733") },
			new Identifier { Name = "Industry", Id = new Guid("a9a5a79d-3648-4a6d-8615-90645a9605de") },
			new Identifier { Name = "Last Name", Id = new Guid("9d2375b0-4530-4e99-a671-0dc5605f2389") },
			new Identifier { Name = "LastMonthSales", Id = new Guid("c558a040-f96c-4407-b75f-39a7a22c7ac6") },
			new Identifier { Name = "Latitude", Id = new Guid("31b12f7e-8804-4a7d-8f22-95725b2ab6eb") },
			new Identifier { Name = "Live Status", Id = new Guid("4c42c3bb-85f5-438d-a19d-bc9d93120a28") },
			new Identifier { Name = "Location Confidence", Id = new Guid("6bf157ad-25ec-42df-99a8-44b89f6e2266") },
			new Identifier { Name = "Location Response Count", Id = new Guid("d26ee6df-b459-41bb-bbd9-0caf3eef29d3") },
			new Identifier { Name = "Location Verification Status", Id = new Guid("b3d1e657-8ae9-4fb2-86c4-424bf185c9a7") },
			new Identifier { Name = "Longitude", Id = new Guid("76ba26ba-a936-4cc6-a08c-f91354956358") },
			new Identifier { Name = "Middle Name", Id = new Guid("5a61e234-0c29-40f7-b08b-b6db4ec5d6c8") },
			new Identifier { Name = "Name Parsing Results", Id = new Guid("ac1bb703-ebb4-4592-b47c-8464186f0356") },
			new Identifier { Name = "Name Parsing Status", Id = new Guid("e3e7beea-1fc6-452e-aab8-dd8b69763902") },
			new Identifier { Name = "PartyType", Id = new Guid("6eb2ee9d-84a3-4ef2-bddb-fe1a641eb270") },
			new Identifier { Name = "PaymentTerms", Id = new Guid("e7b9288b-76f5-4854-880b-b373289e3b83") },
			new Identifier { Name = "Phone Number", Id = new Guid("292132fb-66e1-41a4-99b6-89b719e05545") },
			new Identifier { Name = "Phone Verification Results", Id = new Guid("442c0aa1-d86f-4e9e-bef7-1981cf187935") },
			new Identifier { Name = "Phone Verification Status", Id = new Guid("a30958fc-050c-4115-af87-c3e72576e9d0") },
			new Identifier { Name = "Place Code", Id = new Guid("7d772667-3550-4359-99e4-4212e7e240fc") },
			new Identifier { Name = "Place Name", Id = new Guid("273a179b-4442-4020-b0ca-e284a8c3e9e4") },
			new Identifier { Name = "Plus4", Id = new Guid("1dc537c5-34e0-4da1-960b-eee8d5942d4d") },
			new Identifier { Name = "PMB Name", Id = new Guid("cce65d84-61c3-445c-bf5f-3ba95288e610") },
			new Identifier { Name = "PMB Number", Id = new Guid("d1b24901-1323-41ac-a659-348c0429d94d") },
			new Identifier { Name = "Post Direction", Id = new Guid("f7cb81f5-ff62-4823-a365-6d1980e6e5b6") },
			new Identifier { Name = "Postal Code", Id = new Guid("fe5974d7-e94e-4489-be3e-2fb32a68eb11") },
			new Identifier { Name = "Pre Direction", Id = new Guid("f05d1fde-7bbe-4840-ba82-07c571881958") },
			new Identifier { Name = "Preferred Communication", Id = new Guid("f3455b2e-8ac6-4bf8-a271-0edcd2797c55") },
			new Identifier { Name = "Proposed Count", Id = new Guid("fd4bf09c-c181-48fb-9eab-815a635dc1e3") },
			new Identifier { Name = "Region", Id = new Guid("88bc0d7b-123e-4b0b-a4d0-b2bc4a336492") },
			new Identifier { Name = "Rejection Reason", Id = new Guid("ffbcd6aa-0bf4-4047-ac49-003eefad1d14") },
			new Identifier { Name = "SalesforceID", Id = new Guid("5fd1959e-f5eb-4880-94e8-da6566946bff") },
			new Identifier { Name = "SourceSystem", Id = new Guid("84e53bc0-f6ec-419a-8567-b9926221f982") },
			new Identifier { Name = "StateProvince", Id = new Guid("5b2a058e-bccf-4e03-9381-307934a38fbd") },
			new Identifier { Name = "Status", Id = new Guid("9ad14714-a4b3-4147-bcd6-b53a2357ff92") },
			new Identifier { Name = "Street Name", Id = new Guid("907e6249-6505-4fe4-841e-2ca4de136758") },
			new Identifier { Name = "Street Number", Id = new Guid("44e6da62-9198-4f11-97f5-1d9966557ca1") },
			new Identifier { Name = "Street Suffix", Id = new Guid("2c942f85-675c-4ebf-b0b6-e0fa6fe842b8") },
			new Identifier { Name = "Suite Name", Id = new Guid("b013a5be-581c-42e2-9bcc-2886dd14382c") },
			new Identifier { Name = "Suite Number", Id = new Guid("8234f872-2ebc-4e7b-a81c-c58a727360db") },
			new Identifier { Name = "TaxID", Id = new Guid("f3a7872c-044b-47c1-b604-cdc71c3300d4") },
			new Identifier { Name = "Validation Action", Id = new Guid("f25198fe-95f3-40a5-bce0-575d7342e39a") },
			new Identifier { Name = "WorkflowStatus", Id = new Guid("8ad96d18-7dee-4b0e-ae02-d27adc499497") },
			new Identifier { Name = "ZIP Type", Id = new Guid("49b0a1a8-2bf7-4ec1-b79e-c62f06af2df5") },
		};

		private object _CustomerLocker = new object();

		private void CustomerEntityInitialize()
		{
			lock (_CustomerLocker)
			{
				if ((this.CustomerEntity == null))
				{
					this.CustomerEntity = base.Model.GetEntity<CustomerMember, CustomerMemberAdapter>(LookupBeforeCreate.CustomerEntityId);
				}
			}
		}

		public CustomerMember GetCustomerMember(String memberCode)
		{
			this.CustomerEntityInitialize();
			return this.CustomerEntity.GetMember<CustomerMember>(versionName, memberCode, CustomerAttributes);
		}
		
        public Collection<CustomerMember> GetCustomerMembers(BrowseEntityContext browseContext)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.GetMembers<CustomerMember>(versionName, browseContext, CustomerAttributes);
        }
        
        public Collection<CustomerMember> GetCustomerMembersUsingIds(string name,
            Collection<MemberIdentifier> memberIds)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.GetMembers<CustomerMember>(versionName, memberIds, CustomerAttributes);
        }
        
        public Collection<Error> AddCustomerMember(CustomerMember member)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.AddMember<CustomerMember>(member);
        }
        
        public Collection<Error> AddCustomerMemberWithIdReturn(CustomerMember member, out MemberIdentifier memberId)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.AddMember<CustomerMember>(member, out memberId);
        }
        
        public Collection<Error> AddCustomerMembers(Collection<CustomerMember> members)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.AddMembers<CustomerMember>(members);
        }

		   
        public Collection<Error> AddCustomerMembersWithIdReturn(Collection<CustomerMember> member, out Collection<MemberIdentifier> memberIds)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.AddMembers<CustomerMember>(member, out memberIds);
        }

		public Collection<Error> MergeCustomerMember(CustomerMember member)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.MergeMember<CustomerMember>(member);
        }
        
        public Collection<Error> MergeCustomerMembers(Collection<CustomerMember> members)
		{
            this.CustomerEntityInitialize();
            return this.CustomerEntity.MergeMembers<CustomerMember>(members);
        }
				
		public Collection<Error> UpdateCustomerMember(CustomerMember member)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.UpdateMember<CustomerMember>(member);
        }
        
        public Collection<Error> UpdateCustomerMembers(Collection<CustomerMember> members)
		{
            this.CustomerEntityInitialize();
            return this.CustomerEntity.UpdateMembers<CustomerMember>(members);
        }
		
		public Collection<Error> DeleteCustomerMember(String memberCode)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.DeleteMember(memberCode);
        }
        
        public Collection<Error> DeleteCustomerMembers(Collection<String> memberCodes)
        {
            this.CustomerEntityInitialize();
            return this.CustomerEntity.DeleteMembers(memberCodes);
        }
	}
}
